rootProject.name = "homeaid"
include("user")
include("payment")
include("reservation")
include("board")
include("global")
include("admin")
include("common-domain")
include("review")
include("notification")