services:
  redis:
    image: redis:7-alpine
    container_name: redis
    command: [ "redis-server", "--requirepass", "homeaidpassword" ]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ci-network
    restart: always

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ci-network
    restart: always

networks:
  ci-network:
    external: true

volumes:
  redis_data:
  jenkins_home: